name: Build and Release

on:
  push:
    tags:
      - 'release/*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build & Publish (Ubuntu)
        uses: samuelmeuli/action-electron-builder@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true

      - name: Build Only (Mac & Windows)
        uses: samuelmeuli/action-electron-builder@v1
        if: matrix.os != 'ubuntu-latest'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: false